name: Test code
on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    uses: doplaydo/pdk-ci-workflow-public/.github/workflows/pre_commit.yml@main
  test:
    uses: doplaydo/pdk-ci-workflow-public/.github/workflows/test_code.yml@main
    secrets:
      GFP_API_KEY: ${{ secrets.GFP_API_KEY }}
