name: Auto-label PDK issues
on:
  workflow_call:
  issues:
    types:
      - opened
      - edited
      - deleted
      - pinned
      - unpinned
      - closed
      - reopened
      - assigned
      - unassigned
      - unlabeled
      - locked
      - unlocked
      - transferred
      - milestoned
      - demilestoned
jobs:
  add-label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add label
        run: |
          gh label create "pdk" --force
          gh issue edit ${{ github.event.issue.number }} --add-label "pdk"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
      - name: Add to project
        run: |
          gh project item-add 18 --owner doplaydo --url "${{ github.event.issue.html_url }}"
        env:
          GH_TOKEN: ${{ secrets.PROJECT_TOKEN }}
